spring.application.name=ride-management-service
server.port=5003

# MongoDB Configuration (Environment variable ????? ??????, ??????? default ??? ????? ????)
spring.data.mongodb.uri=${MONGO_URI:mongodb://localhost:27017/ridelink_ride_db}

# Springdoc OpenAPI (Swagger UI) Configuration
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs 