spring.application.name=account-service
spring.config.import=optional:file:.env[.properties]

# Server Port
server.port=5001

# MongoDB Configuration
spring.mongodb.uri=${ACCOUNT_MONGO_URI:mongodb://localhost:27017/ridelink_account_db}
spring.mongodb.database=ridelink_account_db

# JWT Configuration (Environment Variables මඟින් කියවනු ලැබේ)
app.jwt.secret=${RIDE_LINK_JWT_SECRET:${JWT_SECRET}}
app.jwt.expiration-ms=${JWT_EXPIRATION_MS:86400000}

# Swagger UI Path
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

driver-service.base-url=${DRIVER_SERVICE_URL:http://localhost:8082}
driver-service.service-token=${DRIVER_SERVICE_TOKEN:}