spring.application.name=account-service

# Server Port
server.port=5001

spring.data.mongodb.uri=${MONGO_URI}

app.jwt.secret=${JWT_SECRET}
app.jwt.expiration-ms=${JWT_EXPIRATION_MS:86400000}

# Swagger UI Path
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
