spring.application.name=fare-payment-service

server.port=8083
spring.config.import=optional:file:.env[.properties]

spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=ridelink_fare_payment_db

app.jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
app.jwt.expiration-ms=86400000

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

management.endpoints.web.exposure.include=health,info
